name: drupal.nl
recipe: drupal9
config:
  webroot: docroot
  database: mariadb:10.4
  php: '8.2'
services:
  appserver:
    xdebug: true
    config:
      php: .lando/php.ini
    overrides:
      environment:
        # XDEBUG_MODE is left blank to allow for using `lando xdebug debug` tooling command.
        # @see tooling below.
        XDEBUG_MODE:
    run:
      - /app/.lando/xdebug.sh
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
tooling:
  xdebug:
    description: Loads Xdebug in the selected mode. See script for usage.
    cmd:
      - appserver: /app/.lando/xdebug.sh
    user: root
