_core:
  default_config_hash: wB2h-QBawANCiCVEXy6bJjiDfvZY6EONZ6-wRB_RYQc
langcode: en
hotlink: false
origin: 'https://drupal.eu'
origin_dir: sites/default/files
proxy_headers: ''
use_imagecache_root: true
verify: true
