# Dependabot does not run Composer scripts (and by coincedence also plugins).
# This is a major issue making Dependabot useless. This GA workflow fixes that
# by "redoing" the updates with scripts and plugins enabled.

name: Dependabot Workflow
on:
  pull_request:
    branches:
      - main
      - update-dependencies

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    if: ${{ startsWith(github.head_ref, 'dependabot') }}
    uses: lembergsolutions/automation/.github/workflows/dependabot.yml@2.x
    with:
      php_version: ${{ vars.PHP_VERSION }}
      composer_version: ${{ vars.COMPOSER_VERSION }}
