name: Integrate
on:
  pull_request

jobs:
  composer-lock-diff:
    name: integrate
    if: ${{ !startsWith(github.head_ref, 'dependabot') }}
    uses: lembergsolutions/automation/.github/workflows/composer-lock-diff.yml@2.x
    with:
      php_version: ${{ vars.PHP_VERSION }}
      composer_version: ${{ vars.COMPOSER_VERSION }}
